[project]
name = "Schr_dinger-NFT"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/Schr_dinger-NFT/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.Schr_dinger-NFT]
path = "contracts/Schr_dinger-NFT.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
